stages:
- build
- test
- run

build:
  stage: build
  image: rust:latest
  script:
  - cargo build --release
  artifacts:
    paths:
    - target/release/aoc25
    expire_in: 1 hour

test:
  stage: test
  image: rust:latest
  script:
  - cargo test --release
  - cargo clippy -- -D warnings
  - cargo fmt --check

run:
  stage: run
  image: rust:latest
  script:
  - ./target/release/aoc25
  needs:
  - build
